# Generated by Django 5.0 on 2025-12-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_researcher', '0003_superresearcher_address_superresearcher_lead_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superresearcher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
