# Generated by Django 5.2.8 on 2025-11-11 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contact_address_contact_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(choices=[('product_info', 'Product Information'), ('pricing', 'Pricing Inquiry'), ('demo', 'Request Demo'), ('support', 'Technical Support'), ('partnership', 'Partnership Opportunity'), ('custom', 'Custom Message')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
        ),
    ]
