# Generated by Django 5.2.8 on 2025-11-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_remove_sent_emails_body_sent_emails_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquiryLog',
        ),
    ]
