# Generated by Django 5.2.8 on 2025-11-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_alter_contact_lead_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lead_class',
            field=models.CharField(blank=True, choices=[('New', 'New Lead'), ('Contacted', 'Contacted'), ('Growing Interest', 'Growing Interest'), ('Leading', 'Leading'), ('Dying', 'Dying'), ('Converted', 'Converted'), ('Cold', 'Cold')], default='New', max_length=20, null=True),
        ),
    ]
