# Generated by Django 6.0.1 on 2026-01-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_class', models.CharField(choices=[('New', 'New Lead'), ('Contacted', 'Contacted'), ('Growing Interest', 'Growing Interest'), ('Leading', 'Leading'), ('Dying', 'Dying'), ('Converted', 'Converted'), ('Cold', 'Cold')], default='New', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sent_emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=2000, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sent_sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=2000, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
