# Generated by Django 5.2.8 on 2025-11-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
