# Generated by Django 5.2.8 on 2025-11-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_contact_lead_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
