# Generated by Django 5.2.8 on 2025-11-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_sent_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sent_sms',
            name='sent_by',
        ),
    ]
