# Generated by Django 5.2.8 on 2025-11-14 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_remove_sent_sms_sent_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sent_sms',
            name='sent_to',
        ),
        migrations.AddField(
            model_name='sent_sms',
            name='send_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
            preserve_default=False,
        ),
    ]
