# Generated by Django 5.2.8 on 2025-11-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_remove_sent_sms_sent_to_sent_sms_send_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sent_sms',
            old_name='send_to',
            new_name='contact',
        ),
    ]
