# Generated by Django 5.0 on 2025-11-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_rename_send_to_sent_sms_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Full_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
