# Generated by Django 5.0 on 2025-12-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_remove_contact_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
