# Generated by Django 5.0 on 2025-12-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0003_apex_research_address_apex_research_lead_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apex_research',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
